services:
  php:
    build:
      context: ./docker/php-8.2-fpm
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    container_name: laravel-php
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    # ports:
    #   - "8000:8000"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
